version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=791156
    restart: always

  api:
    build:
      context: .
      dockerfile: Controller/Dockerfile
    container_name: exe-api-backend
    ports:
      - "8000:8080"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://root:791156@mongodb:27017
      - MongoDB__DatabaseName=Exe_DB
    restart: always

volumes:
  mongodb_data:
    name: mongodb_data
